# -*- coding: utf-8 -*-
"""Mini_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10vKr5GW4zWXzD3iDJwDd7iPufZWMWVi3

# **A Mini-Project to Clean a Messy Student Survey data**

**The imports**
"""

import pandas as pd
import numpy as np
import io
import re # regex (pattern matching) for cleaning messy text like "16 years"

# 2. Load the deliberately messy CSV dataset (20 rows, 10 columns)
csv_data = """student_id,age,grade_level,gender,device_type,internet_quality,satisfaction_rating,hours_online_learning,preferred_learning,feedback
1,16,10,Female,Laptop,Good,8,5,Video,"Great experience, learned a lot"
2,seventeen,11,M,tablet,excellent,9,6,Interactive,"Good but need better audio"
3,16 years,10,FEMALE,laptop,Poor,3,2,reading,""
4,999,12,Male,Desktop,good,7,4,video,"Okay experience"
5,15,9,f,Phone,Bad,2,1,interactive,"Very difficult with poor internet"
6,16,10,Female,Laptop,Good,8,5,Video,"Great experience, learned a lot"
7,18,12,male,LAPTOP,Excellent,15,8,Mixed,"Excellent program!"
8,,11,Female,Tablet,Fair,6,3,Reading,"Missing some features"
9,14,9,M,laptop,good,5,4,video,""
10,16,10,f,Desktop,Poor,4,3,Interactive,"Need better support"
11,17,11,Male,Phone,excellent,8,6,mixed,"Good overall"
12,-5,8,Female,Laptop,Good,1,0,Video,"Too young for this"
13,16,10,MALE,tablet,Bad,3,2,reading,"Hard to focus"
14,150,12,F,Desktop,Fair,7,5,Interactive,"Interesting but long"
15,sixteen,10,female,Laptop,Good,9,7,Video,"Loved it!"
16,17,11,,Tablet,excellent,6,4,Reading,"Good content"
17,15,9,Male,laptop,poor,2,1,video,"Technical issues"
18,16,10,Female,Desktop,Good,8,5,Mixed,"Great experience"
19,18,12,m,Phone,Excellent,7,6,interactive,"Good but challenging"
20,16,10,FEMALE,Laptop,good,20,5,Video,"Best program ever!\""""

df = pd.read_csv(io.StringIO(csv_data))
print("Loaded:", df.shape)
df.head()

df.describe()

"""**M1) Remove duplicate submissions**"""

# If a student accidentally submitted the survey twice, we keep only the first record.
df = df.drop_duplicates(subset="student_id")
print("Removed duplicates:", df.shape)
print(df["age"])

"""**M2) Make age numeric**"""

# The "age" column is messy: values like "sixteen", "16 years", or even invalid numbers like 999.

# Step 1: Convert everything to lowercase strings
ages = df["age"].astype(str).str.lower().str.strip()

# Step 2: replace written words with digit strings
word_to_num = {
    "fourteen": "14",
    "fifteen": "15",
    "sixteen": "16",
    "seventeen": "17",
    "eighteen": "18"
}
ages = ages.replace(word_to_num)

# Step 3: FIXED - remove non-digit characters but keep decimal points
ages = ages.apply(lambda x: re.sub(r"[^0-9.]", "", str(x)))

# Step 4: convert to numeric (invalid strings -> NaN)
df["age"] = pd.to_numeric(ages, errors="coerce")

# Step 5: ADD THIS - handle unrealistic ages
df["age"] = df["age"].apply(lambda x: x if pd.isna(x) or (5< x <= 120) else np.nan)

# Then fill missing ages with the median within the same grade_level group.
df["age"] = df.groupby("grade_level")["age"].transform(lambda x: x.fillna(x.median()))

print(df["age"])

"""**M4) Standardize gender categories**"""

print("Gender counts:\n", df["gender"].value_counts(dropna=False), "\n")

# Gender column has values like "M", "male", "FEMALE", "f".
# We standardize them to "Male" or "Female".
gmap = {"m": "Male", "male": "Male", "f": "Female", "female": "Female"}
df["gender"] = df["gender"].astype(str).str.strip().str.lower().map(gmap)
print("Gender counts:\n", df["gender"].value_counts(dropna=False), "\n")
print(df["gender"])

"""**M5) Force ratings onto a 1–10 scale**"""

# Convert to numeric, force onto [1, 10].
df["satisfaction_rating"] = pd.to_numeric(df["satisfaction_rating"], errors="coerce").clip(1, 10)
print("Ratings summary:\n", df["satisfaction_rating"].describe(), "\n")

"""**M6) Tidy text columns**"""

# Clean device_type, internet_quality, preferred_learning, feedback:
for c in ["device_type", "internet_quality", "preferred_learning", "feedback"]:
    s = df[c].astype(str).str.strip()
    s = s.mask(s.eq("") | s.eq("nan"))       # empty strings → NaN
    df[c] = s.where(s.isna(), s.str.title()) # TitleCase if not missing
print("Missing values per column:\n", df.isna().sum(), "\n")

"""**M7) Final check**"""

# Confirm types are correct and data is reasonable.
df.info()
print(df.head(), "\n")

# Question: What is the median age for students in grade_level == 10 (after cleaning)?
value_to_submit = round(df.loc[df["grade_level"] == 10, "age"].median(), 2)
print("Value to submit:", value_to_submit)