# -*- coding: utf-8 -*-
"""NUMPY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHkYvO7Ji4qVkuPlpsNAZ-i4-R_frMz4
"""

import numpy as np
list1=[1,2,3,4]*2
print(list1)
arr1=np.array([1,2,3,4])*2
print(arr1)

array=np.array([[[ 'A','B','C'],['D','E','F'],['G','H','I']],
               [[ 'J','K','L'],['M','N','O'],['P','Q','R']],
               [[ 'A','B','C'],['D','E','F'],['G','H','I']]])
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)
print(array.itemsize)
print(array.data)
print(array[0][0][0])
print(array[0,0,1])
word=array[1,1,0]+array[0,0,0]+array[1,1,1]
print(word)

#slicing
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                 [13,14,15,16]])

#array[start:end:step]
#print(array[0])
print(array[::2])
print(array[:,-1])

print(array[:,::-2])
print(array[2:,1:3])
print(array[2:,2:])

#arithmetic
#scalar

array=np.array([1,2,3])
print(array+1)
print(array-1)
print(array*2)
print(array/2)
print(array**3)

#vectorized math functions
array=np.array([1,2,3])
print(np.sqrt(array))
print(np.log(array))
print(np.exp(array))
print(np.amax(array))
print(np.pi*array**2)

scores=np.array([60,70,75,80,90,98])
print(scores[scores>70])
scores[scores<70]=0
print(scores)
print(scores==80)
print(scores<=80)

# broadcasting
#number of columns should match or have a 1
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3]])
print(array1+array2)
print(array1*array2)
print(array1.shape)
print(array2.shape)

array1=np.array([[1,2,3,4,5,6,7,8,9,10]])
array2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1.shape)
print(array2.shape)

print(array1*array2)

#Aggregate functions= summarize data and typically return a single value

array=np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))
print(np.sum(array,axis=0))
print(np.sum(array,axis=1))

#Filtering= process of selecting elements from an array that match a given condition
ages=np.array([[20,21,22,14,18,16,15,25],
              [26,30,60,55,23,13,17,40]])
teenagers=ages[ages<18]
print(teenagers)